---
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: orders-db-access
  namespace: default
spec:
  podSelector:
    matchLabels:
      name: orders-db
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: orders
      ports:
        - protocol: TCP
          port: 27017
