---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prism
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: prism
    spec:
      containers:
      - name: prism
        image: tomwilkie/prometheus:34ed558
        imagePullPolicy: IfNotPresent
        args:
        - -config.file=/etc/prometheus/prometheus.yml
        - -web.listen-address=:80
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prism-config
